//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccAcademyBookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int ID_Book { get; set; }
        public string BookTitle { get; set; }
        public Nullable<int> Author { get; set; }
        public Nullable<int> Genre { get; set; }
        public Nullable<int> Publisher { get; set; }
        public string ISBN { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Genres Genres { get; set; }
        public virtual Publisher Publisher1 { get; set; }
    }
}
